# Generated by Django 3.2.15 on 2022-10-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexandria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
